name: Keep Render App Awake

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://insightops-backend.onrender.com/)
          echo "Response code: $RESPONSE"
